# Generated by Django 5.1.2 on 2026-02-13 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tried_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz - Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('coach', 'coach'), ('general', 'general')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_logined', models.DateTimeField(blank=True, null=True)),
                ('token', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User - Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('job_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Background Job',
                'verbose_name_plural': 'Task - Background Jobs',
                'db_table': 'background_jobs',
                'indexes': [models.Index(fields=['job_type', 'created_at'], name='background__job_typ_d149d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(default='[]')),
                ('correct', models.TextField()),
                ('wrong', models.TextField()),
                ('explanation', models.TextField()),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz - Quiz Questions',
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
                ('question', models.ForeignKey(db_column='quiz_question_id', on_delete=django.db.models.deletion.CASCADE, related_name='correct_entries', to='app.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Correct Answer',
                'verbose_name_plural': 'Quiz - Quiz Correct Answers',
                'db_table': 'quiz_corrects',
            },
        ),
        migrations.CreateModel(
            name='QuizWrong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(db_column='quiz_question_id', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_entries', to='app.quizquestion')),
                ('quiz', models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='app.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Wrong Answer',
                'verbose_name_plural': 'Quiz - Quiz Wrong Answers',
                'db_table': 'quiz_wrongs',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('is_wrong', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(db_column='quiz_question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.quizquestion')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='app.user')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz - Quiz Answers',
                'db_table': 'quiz_answers',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.user'),
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='general_profile', to='app.user')),
            ],
            options={
                'verbose_name': 'General User',
                'verbose_name_plural': 'User - General Users',
                'db_table': 'general_users',
            },
        ),
        migrations.CreateModel(
            name='CoachUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='app.user')),
            ],
            options={
                'verbose_name': 'Coach User',
                'verbose_name_plural': 'User - Coach Users',
                'db_table': 'coach_users',
            },
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('summary_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_summaries', to='app.user')),
            ],
            options={
                'verbose_name': 'Chat Summary',
                'verbose_name_plural': 'Chat - Chat Summaries',
                'db_table': 'chat_summaries',
            },
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_records', to='app.user')),
            ],
            options={
                'verbose_name': 'Chat Record',
                'verbose_name_plural': 'Chat - Chat Records',
                'db_table': 'chat_records',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='app.user')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'User - Admin Users',
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField()),
                ('wrong_answer', models.TextField()),
                ('reference_link', models.TextField()),
                ('user_answers', models.TextField()),
                ('last_solved_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(db_column='quiz_question_id', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='app.quizquestion')),
                ('question_creator', models.ForeignKey(db_column='question_creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_wrong_questions', to='app.user')),
                ('solver_user', models.ForeignKey(db_column='solver_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='solved_wrong_questions', to='app.user')),
            ],
            options={
                'verbose_name': 'Wrong Question',
                'verbose_name_plural': 'Quiz - Wrong Questions',
                'db_table': 'wrong_questions',
            },
        ),
        migrations.CreateModel(
            name='CoachStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coach', models.ForeignKey(db_column='coach_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.coachuser')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='app.generaluser')),
            ],
            options={
                'verbose_name': 'Coach-Student Relation',
                'verbose_name_plural': 'User - Coach-Student Relations',
                'db_table': 'coach_students',
                'constraints': [models.UniqueConstraint(fields=('coach', 'student'), name='uniq_coach_student')],
            },
        ),
    ]
